
export default new Map([
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_1/cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_1%2Fcheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_2/cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_2%2Fcheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_2/course.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_2%2Fcourse.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_1/course.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_1%2Fcourse.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_2/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_2%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/antigravity/cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fantigravity%2Fcheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/ai_example_1/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fai_example_1%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/antigravity/course.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fantigravity%2Fcourse.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/antigravity/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fantigravity%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/alex/cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Falex%2Fcheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/alex/course.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Falex%2Fcourse.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/alex/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Falex%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/claire/course.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fclaire%2Fcourse.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/claire/cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fclaire%2Fcheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/docs/contributors/claire/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontributors%2Fclaire%2Findex.mdx&astroContentModuleFlag=true")]]);
		